//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ravioli.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbArtigo> tbArtigo { get; set; }
        public DbSet<tbArtigoCategoria> tbArtigoCategoria { get; set; }
        public DbSet<tbArtigoCategoriaStatus> tbArtigoCategoriaStatus { get; set; }
        public DbSet<tbArtigoComentario> tbArtigoComentario { get; set; }
        public DbSet<tbArtigoComentarioStatus> tbArtigoComentarioStatus { get; set; }
        public DbSet<tbArtigoCompartilhado> tbArtigoCompartilhado { get; set; }
        public DbSet<tbArtigoStatus> tbArtigoStatus { get; set; }
        public DbSet<tbArtigoTags> tbArtigoTags { get; set; }
        public DbSet<tbHistorico> tbHistorico { get; set; }
        public DbSet<tbHistoricoTipo> tbHistoricoTipo { get; set; }
        public DbSet<tbNotificacao> tbNotificacao { get; set; }
        public DbSet<tbNotificacaoAcao> tbNotificacaoAcao { get; set; }
        public DbSet<tbNotificacaoAlvo> tbNotificacaoAlvo { get; set; }
        public DbSet<tbNotificacaoTipo> tbNotificacaoTipo { get; set; }
        public DbSet<tbPrato> tbPrato { get; set; }
        public DbSet<tbPratoCategoria> tbPratoCategoria { get; set; }
        public DbSet<tbPratoCategoriaStatus> tbPratoCategoriaStatus { get; set; }
        public DbSet<tbPratoRestaurante> tbPratoRestaurante { get; set; }
        public DbSet<tbPratoStatus> tbPratoStatus { get; set; }
        public DbSet<tbReserva> tbReserva { get; set; }
        public DbSet<tbReservaOrigem> tbReservaOrigem { get; set; }
        public DbSet<tbReservaStatus> tbReservaStatus { get; set; }
        public DbSet<tbRestaurante> tbRestaurante { get; set; }
        public DbSet<tbRestauranteStatus> tbRestauranteStatus { get; set; }
        public DbSet<tbUsuario> tbUsuario { get; set; }
        public DbSet<tbUsuarioCargo> tbUsuarioCargo { get; set; }
        public DbSet<tbUsuarioCargoStatus> tbUsuarioCargoStatus { get; set; }
        public DbSet<tbUsuarioDepartamento> tbUsuarioDepartamento { get; set; }
        public DbSet<tbUsuarioDepartamentoStatus> tbUsuarioDepartamentoStatus { get; set; }
        public DbSet<tbUsuarioExterno> tbUsuarioExterno { get; set; }
        public DbSet<tbUsuarioExternoStatus> tbUsuarioExternoStatus { get; set; }
        public DbSet<tbUsuarioExternoTipoPerfil> tbUsuarioExternoTipoPerfil { get; set; }
        public DbSet<tbUsuarioNivel> tbUsuarioNivel { get; set; }
        public DbSet<tbUsuarioNotificacao> tbUsuarioNotificacao { get; set; }
        public DbSet<tbUsuarioStatus> tbUsuarioStatus { get; set; }
    }
}
