//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ravioli.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbArtigo
    {
        public tbArtigo()
        {
            this.tbArtigoComentario = new HashSet<tbArtigoComentario>();
            this.tbArtigoCompartilhado = new HashSet<tbArtigoCompartilhado>();
        }
    
        public int id { get; set; }
        public string titulo { get; set; }
        public string subtitulo { get; set; }
        public string imgThumb { get; set; }
        public string conteudo { get; set; }
        public int usuarioId { get; set; }
        public int statusId { get; set; }
        public int categoriaId { get; set; }
        public System.DateTime dtCriacao { get; set; }
        public Nullable<System.DateTime> dtPublicacaoInicio { get; set; }
        public Nullable<System.TimeSpan> hrPublicacaoInicio { get; set; }
        public Nullable<System.DateTime> dtPublicacaoFim { get; set; }
        public Nullable<System.TimeSpan> hrPublicacaoFim { get; set; }
        public string nomeAutor { get; set; }
    
        public virtual ICollection<tbArtigoComentario> tbArtigoComentario { get; set; }
        public virtual ICollection<tbArtigoCompartilhado> tbArtigoCompartilhado { get; set; }
    }
}
