//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ravioli.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbArtigoCompartilhado
    {
        public int id { get; set; }
        public string ip { get; set; }
        public System.DateTime dtCompartilhado { get; set; }
        public int artigoId { get; set; }
        public int usuarioExternoId { get; set; }
    
        public virtual tbArtigo tbArtigo { get; set; }
        public virtual tbUsuarioExterno tbUsuarioExterno { get; set; }
    }
}
