//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ravioli.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbNotificacao
    {
        public tbNotificacao()
        {
            this.tbUsuarioNotificacao = new HashSet<tbUsuarioNotificacao>();
        }
    
        public int id { get; set; }
        public Nullable<int> artigoId { get; set; }
        public Nullable<int> pratoId { get; set; }
        public Nullable<int> restauranteId { get; set; }
        public Nullable<int> usuarioId { get; set; }
        public Nullable<int> usuarioExternoId { get; set; }
        public int tipoId { get; set; }
        public int acaoId { get; set; }
        public int alvoId { get; set; }
        public string mensagem { get; set; }
    
        public virtual tbNotificacaoAcao tbNotificacaoAcao { get; set; }
        public virtual tbNotificacaoAlvo tbNotificacaoAlvo { get; set; }
        public virtual tbNotificacaoTipo tbNotificacaoTipo { get; set; }
        public virtual ICollection<tbUsuarioNotificacao> tbUsuarioNotificacao { get; set; }
    }
}
