//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ravioli.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbReserva
    {
        public int id { get; set; }
        public System.DateTime dtCriacao { get; set; }
        public System.DateTime dataReserva { get; set; }
        public System.TimeSpan horaReserva { get; set; }
        public int pessoasReserva { get; set; }
        public string observacao { get; set; }
        public bool favoritado { get; set; }
        public Nullable<int> usuarioId { get; set; }
        public int restauranteId { get; set; }
        public int statusId { get; set; }
        public int origemId { get; set; }
        public int usuarioExternoId { get; set; }
        public bool efetuado { get; set; }
    
        public virtual tbReservaOrigem tbReservaOrigem { get; set; }
        public virtual tbReservaStatus tbReservaStatus { get; set; }
        public virtual tbRestaurante tbRestaurante { get; set; }
        public virtual tbUsuarioExterno tbUsuarioExterno { get; set; }
    }
}
