//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ravioli.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsuario
    {
        public tbUsuario()
        {
            this.tbHistorico = new HashSet<tbHistorico>();
            this.tbPrato = new HashSet<tbPrato>();
            this.tbRestaurante = new HashSet<tbRestaurante>();
            this.tbUsuarioNotificacao = new HashSet<tbUsuarioNotificacao>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
        public string senha { get; set; }
        public int restauranteId { get; set; }
        public int departamentoId { get; set; }
        public int statusId { get; set; }
        public int nivelId { get; set; }
        public int cargoId { get; set; }
        public Nullable<int> usuarioId { get; set; }
        public string sobre { get; set; }
        public string caminhoFoto { get; set; }
    
        public virtual ICollection<tbHistorico> tbHistorico { get; set; }
        public virtual ICollection<tbPrato> tbPrato { get; set; }
        public virtual ICollection<tbRestaurante> tbRestaurante { get; set; }
        public virtual tbUsuarioCargo tbUsuarioCargo { get; set; }
        public virtual tbUsuarioDepartamento tbUsuarioDepartamento { get; set; }
        public virtual tbUsuarioNivel tbUsuarioNivel { get; set; }
        public virtual tbUsuarioStatus tbUsuarioStatus { get; set; }
        public virtual ICollection<tbUsuarioNotificacao> tbUsuarioNotificacao { get; set; }
    }
}
