//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ravioli.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsuarioExterno
    {
        public tbUsuarioExterno()
        {
            this.tbArtigoComentario = new HashSet<tbArtigoComentario>();
            this.tbArtigoCompartilhado = new HashSet<tbArtigoCompartilhado>();
            this.tbReserva = new HashSet<tbReserva>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
        public string celular { get; set; }
        public string telefone { get; set; }
        public int tipoPerfilId { get; set; }
        public int statusId { get; set; }
    
        public virtual ICollection<tbArtigoComentario> tbArtigoComentario { get; set; }
        public virtual ICollection<tbArtigoCompartilhado> tbArtigoCompartilhado { get; set; }
        public virtual ICollection<tbReserva> tbReserva { get; set; }
        public virtual tbUsuarioExternoStatus tbUsuarioExternoStatus { get; set; }
        public virtual tbUsuarioExternoTipoPerfil tbUsuarioExternoTipoPerfil { get; set; }
    }
}
