//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ravioli.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsuarioNotificacao
    {
        public int id { get; set; }
        public int usuarioId { get; set; }
        public int notificacaoId { get; set; }
        public bool notificacaoLido { get; set; }
    
        public virtual tbNotificacao tbNotificacao { get; set; }
        public virtual tbUsuario tbUsuario { get; set; }
    }
}
